config/routes.rb
Rails.application.routes.draw do
    get "/pages/about" => "pages#about", as: :about
    get "pages/contact" => "pages#contact", as: :contact
    # get "/posts" => "posts#index", as: :posts
    # post "posts/" => "posts#create"
    # get "/post/new" => "posts#new", as: :new_post
    # get "/post/:id" => "posts#show", as: :post
    # get "/post/:id/edit" => "posts#edit", as: :edit_post
    # patch "/post/:id" => "posts#update"
    # delete "/post/:id" => "posts#destroy", as: :destroy

    resources :posts do
        resources :comments
    end

end

app/models/comment.rb
class Comment < ActiveRecord::Base
    # association to posts
  belongs_to :post
end

app/models/post.rb
class Post < ActiveRecord::Base
    validates :title, presence: true
    validates :body, presence: true

    validates :title, length: {minimum: 5}
    validates :body, length: {minimum: 20}
    # association link
    has_many :comments

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    def create
        # find the post by id
        @post = Post.find(params[:post_id])
            #create a new commnet from the params given
        @comment = @post.comments.create(comment_params)
        flash[:notice] = "Comment has been created"
        redirect_to post_path(@post)
    end

    def destroy
        # find the post by id
        @post = Post.find(params[:post_id])
        #find the comment by the given id
        @comment = @post.comments.find(params[:id])
        #delete
        @comment.destroy
        flash[:notice] = "Comment has been deleted"
        #return to the given path
        redirect_to post_path(@post)
    end

    private
    # allow parameters to be passed
    def comment_params
        params.require(:comment).permit(:name, :body)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
    def about
        @christian = "Chrisitan"
        # render :contact
    end

    def contact
        @christian = "gonzo"
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
    before_action :find_post, only: [:show, :edit, :update, :destroy]
    def index
        @posts = Post.all.order("created_at DESC")
    end
    # make a new post
    def new
        @post = Post.new
    end

    def create
        # make a new post based on the given paramters
        @post = Post.new(post_params)
        # if we saved corrently, flash message and go to page
        if  @post.save
            flash[:notice] = "Post successfully created"
            redirect_to post_path(@post)
        else
            render :new
        end

    end

    def show
    end

    def edit
    end

    def destroy
        @post.destroy
        flash[:notice] = "Post successfully deleted :*("

        redirect_to posts_path
    end

    def update
        if @post.update(post_params)
        flash[:notice] = "Post successfully updated"

        redirect_to post_path@post
    else
        render :edit
        end

    end

    private
    # DRY finding post
    def find_post
        @post = Post.find(params[:id])
    end
    #allow parameters to be passed
    def post_params
        params.require(:post).permit(:title, :body)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/comments/_comment.html.erb
<div class="comments">
    <p><strong><%= comment.name %></strong>

    </p>
    <p>
            <%= comment.body %>
    </p>

<p>
    <!--  link to delete method in controller, pass data, method, and alert message-->
    <%= link_to "delete", [comment.post, comment], method: :delete, data: {confirm: "are you sure?"} %>
</p>


</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Myblog</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<% if flash[:notice] %>
    <div>
        <% flash[:notice] %>
    </div>
    <% end %>
<%= yield %>

</body>
</html>

app/views/pages/about.html.erb
<%= react_component('About', {prerender: false, christian: @christian}) %>
<div>
<%link_to("About", ) %>
</div>

<div>
    <%= image_tag("venus.jpeg") %>
</div>

app/views/pages/contact.html.erb
<h2>suhhhhh</h2>
<%= react_component('Contact', {prerender: false, christian: @christian}) %>

<% link_to("About", about_path ) %>

app/views/posts/_form.html.erb
<%= link_to "back", posts_path %>

<div>

        <% if @post.errors.any?  %>
        <ul>
            <% @post.errors.full_messages.each do |message| %>
            <li>
                    <%= message %>
            </li>
            <% end %>
            </ul>
        <% end %>



    <%= form_for @post do |f| %>
        <%= f.label :title %>
        <%= f.text_field :title %>

        <%= f.label :body %>

        <%= f.text_area :body %>
        <%=f.submit %>
    <% end %>
</div>

app/views/posts/edit.html.erb
<p>
    post for <%=params[:id] %>
     <%= link_to "back", posts_path %>
</p>

<div className="panel">
    <%= form_for @post do |f| %>
        <%= f.label :title %>
        <%= f.text_field :title %>

        <%= f.label :body %>

        <%= f.text_area :body %>
        <%=f.submit %>
    <% end %>
</div>

app/views/posts/index.html.erb
<%= link_to "New Post", new_post_path %>
<% @posts.each do |post| %>
    <div class="panel">
        <h2>
            <%= link_to post.title, post_path(post) %>


        </h2>
        <p>
                <%= post.body %>
        </p>
        <%= link_to "edit", edit_post_path(post) %> |
        <%= link_to "delete", post_path(post), method: :delete, data: {confirm: "Are you sure?"} %>
    </div>

    <% end %>

app/views/posts/new.html.erb
<%= link_to "back", posts_path %>

<%= render "form" %>

app/views/posts/show.html.erb
<%= link_to "back", posts_path %>
<p>
    <%= params[:id]%>
</p>
<p>
    <%= @post.title %>
    <%= @post.body %>
</p>

<p>
    <%= link_to "edit", edit_post_path %> | <%= link_to "delete", post_path(@post), method: :delete, data: {confirm: "Are you sure?"} %>
</p>

<h3>Comments</h3>
<!--  pulls comment partial, orders by most recent-->
<%= render @post.comments.order("created_at DESC") %>

<h4>Add Comment</h4>
<!--  makes a basic form the necessary info for comments, corresponding to schema-->
<%= form_for [@post, @post.comments.build] do |f|  %>
    <%= f.label :name %><br />
    <%= f.text_field :name %><br />

    <%= f.label :body %><br />
    <%= f.text_field :body %><br />

    <%= f.submit  %><br />
<% end %>